language: python
python:
- 3.7
- 3.8
cache:
  pip: true
install:
- pip install .
script:
- python -m unittest discover ./test/ -v
before_deploy:
- poetry config pypi-token.pypi $PYPI_TOKEN
- poetry build 
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true